### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by zachlatta** [emacsconf/emacsconf2015#17]
Is this still happening?

**Comment by jjasghar** [comment]
When & Where?
EmacsConf will be on August 29nd (a Saturday). The IRL component will be in the GoodShop San Francisco office at 550 Montgomery St, San Francisco, CA, and Sacha will be hosting an online component. All of the talks and events will be livestreamed.

**Comment by zachlatta** [comment]
Awesome – thanks so much. Has the schedule been finalized eyt?

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us/
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by samertm** [comment]
Still happening! The talk schedule is being finalized now, but it will be between 9am and 7pm, which snacks and food provided.

Thinking of bringing some new blood to the conference? :smiley:

**Comment by zachlatta** [comment]
Arghh, I wish I could make it. I'm travelling that day.

Would have brought the team! So far I've converted one other member... soon
to be more.

On Tue, Aug 11, 2015 at 3:29 PM, Samer Masterson notifications@github.com
wrote:

> Still happening! The talk schedule is being finalized now, but it will be
> between 9am and 7pm, which snacks and food provided.
> 
> Thinking of bringing some new blood to the conference? [image: :smiley:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/emacsconf/emacsconf2015/issues/17#issuecomment-130097493
> .

## 

Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by samertm** [comment]
Aw, that's a bummer! We need to hang out soon :)

We'll have recordings of the talks up on emacsconf2015.org, so you won't miss the whole thing.

**Comment by zachlatta** [comment]
Looking forward to seeing them!

On Tue, Aug 11, 2015 at 4:52 PM, Samer Masterson notifications@github.com
wrote:

> Aw, that's a bummer! We need to hang out soon :)
> 
> We'll have recordings of the talks up on emacsconf2015.org, so you won't
> miss the whole thing.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/emacsconf/emacsconf2015/issues/17#issuecomment-130114559
> .

## 

Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta
